[browser]
gatherUsageStats = false

[pages]
[pages.Administracion]
disabled = true

[pages.ConsultasMedicas]
disabled = true

[pages.Estudios]
disabled = true

[pages.Medicamentos]
disabled = true

[pages.HistorialClinico]
disabled = true
